### increment a post views
GET http://localhost:8787/post1

### get a post views
GET http://localhost:8787/post1
Content-Type: application/json

### get views list for all posts
GET http://localhost:8787/?views

